spring:
  profiles:
    include: fileupload
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  redisson:
    host: 127.0.0.1
    port: 63179
    password: 1qaz@WSX
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
  cache:
    redis:
      key-prefix: gzgjjApi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.33.11:3306/spring-security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    hikari:
      pool-name: test

logging:
  file:
    max-history: 50
    max-size: 5MB
  level:
    root: info
    org:
      hibernate:
        SQL: debug
      springframework:
        boot:
          autoconfigure: error
    com:
      eyoung: debug
#  path: ../logs/gzgjj/gzgjjWx

server:
  port: 8080
  servlet:
    context-path: /spring_security

domainPage: http://zyy.gdtengnan.com${server.servlet.context-path}

weixin:
  appId:
  secret:
